CREATE TABLE [dbo].[AFP] (
    [Id]   INT           IDENTITY (1, 1) NOT NULL,
    [Name] VARCHAR (128) NOT NULL,
    [NIT]  VARCHAR (20)  NOT NULL,
    CONSTRAINT [PK__AFP__3214EC07B412BB6A] PRIMARY KEY CLUSTERED ([Id] ASC)
);



