CREATE TABLE [dbo].[EPS] (
    [Id]   INT           IDENTITY (1, 1) NOT NULL,
    [Name] VARCHAR (128) NOT NULL,
    [NIT]  VARCHAR (20)  NOT NULL,
    CONSTRAINT [PK__EPS__3214EC07732FFA91] PRIMARY KEY CLUSTERED ([Id] ASC)
);



