//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLogisticsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Holding = new HashSet<Holding>();
        }
    
        public int Id { get; set; }
        public long DocumentNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime BornDate { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string MobilePhone { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyContactPhone { get; set; }
        public int MaritalStatusId { get; set; }
        public int AfpId { get; set; }
        public int EpsId { get; set; }
        public string Comments { get; set; }
        public bool CV { get; set; }
        public bool DocumentCopy { get; set; }
        public bool Photos { get; set; }
        public bool MilitaryIdCopy { get; set; }
        public bool LaborCertification { get; set; }
        public bool PersonalReference { get; set; }
        public bool DisciplinaryBackground { get; set; }
        public bool KnowledgeTest { get; set; }
        public bool AdmissionTest { get; set; }
        public bool Contract { get; set; }
        public bool InternalRegulations { get; set; }
        public bool EndownmentLetter { get; set; }
        public bool CriticalPosition { get; set; }
    
        public virtual AFP AFP { get; set; }
        public virtual EPS EPS { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Holding> Holding { get; set; }
    }
}
