//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLogisticsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDocuments
    {
        public int EmployeeId { get; set; }
        public bool CV { get; set; }
        public bool DocumentCopy { get; set; }
        public bool Photos { get; set; }
        public bool MilitaryIdCopy { get; set; }
        public bool LaborCertification { get; set; }
        public bool PersonalReference { get; set; }
        public bool DisciplinaryBackground { get; set; }
        public bool KnowledgeTest { get; set; }
        public bool AdmissionTest { get; set; }
        public bool Contract { get; set; }
        public bool InternalRegulations { get; set; }
        public bool EndownmentLetter { get; set; }
        public bool CriticalPosition { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
