//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLogisticsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int ActivityId { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public int Price { get; set; }
        public int PercentCost { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Client Client { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
